### ISSUE TITLE
When adding use statements, make the sorted alphabetically

### ISSUE THREAD

**Issue by pjedrzejewski** [umpirsky/Symfony-Upgrade-Fixer#13]
:)

**Comment by umpirsky** [comment]
I think we can reuse PHP CS Fixer `ordered_use` fixer for this.

**Comment by umpirsky** [comment]
Fixed in https://github.com/umpirsky/Symfony-Upgrade-Fixer/commit/180d267fe05315f3b8bfe6aa7b2925960aca555d.

**Comment by pjedrzejewski** [comment]
:+1:
