### ISSUE TITLE
entity form type not replaced with EntityType::class

### ISSUE THREAD

**Issue by kristijanhusak** [umpirsky/Symfony-Upgrade-Fixer#16]
[FormTypeNamesFixer](https://github.com/umpirsky/Symfony-Upgrade-Fixer/blob/master/src/Symfony/Upgrade/Fixer/FormTypeNamesFixer.php) fixes all core types except [entity type](https://github.com/umpirsky/Symfony-Upgrade-Fixer/blob/master/src/Symfony/Upgrade/Fixer/FormTypeNamesFixer.php)

I know it's not possible to simply add it to this fixer because namespace is different, but this should be added with some conditions.

**Comment by althaus** [comment]
Would be great to add custom form types through some kind of config in that situaton, too.
