### ISSUE TITLE
Some deprecations getRequest not fixed

### ISSUE THREAD

**Issue by PatrickLEBRUN** [umpirsky/Symfony-Upgrade-Fixer#33]
Hello,

I have run Upgrade-Fixer on my projet Symfony 2.8
Some deprecations on getRequest are not fixed.
For example, this extract of code is not corrected : 

protected function getSortParameters($route)
{
    $sort = $this->getRequest()->get('tri');
    $dir  = $this->getRequest()->get('ordre');
    $uri = $this->getRequest()->getRequestUri();
    $posQueryStr = explode('?', $uri);

Do you know why ?

Thanks,

P.LEBRUN

**Comment by umpirsky** [comment]
This tool just gives you some wind in the back by fixing some deprecations. The rest is up to you.
