### ISSUE TITLE
Just a note about fixers ported to Rector

### ISSUE THREAD

**Issue by TomasVotruba** [umpirsky/Symfony-Upgrade-Fixer#40]
Hey, I love your rules. They are easy to understand and read, thanks for clean code.

Firstly, **thank you for this tool and inspiration it gave me!**

I just wanted to let you know I've ported them to [@RectorPHP](https://github.com/RectorPHP), where I build AST-refactoring tool for all frameworks and their versions.

All rules to be found in `symfony30.yml`: https://github.com/RectorPHP/Rector/blob/f0036936989df22493122abe60b7843a4ad31bf1/src/config/level/symfony/symfony30.yml

PR: https://github.com/RectorPHP/Rector/pull/103

**I'd be happy for any feedback or new rules.**

**Comment by umpirsky** [comment]
Great, I'm glad you liked it, thanks for your contribution!
