### ISSUE TITLE
The "--dry-run" option does not exist.  

### ISSUE THREAD

**Issue by bruno-ds** [umpirsky/Symfony-Upgrade-Fixer#42]
Hello,

Having Symfony Upgrade Fixer 0.1.6 installed globally using composer, 

if I run `symfony-upgrade-fixer  --dry-run` I've got this error message : 
> The "--dry-run" option does not exist.

**Comment by umpirsky** [comment]
Yes, there is no `--dry-run` option. It was never planned. If someone wants to implement it, I'l accept PR.

**Comment by umpirsky** [comment]
Try `symfony-upgrade-fixer fix /path/to/code --dry-run`.

**Comment by bruno-ds** [comment]
thank you, `symfony-upgrade-fixer fix /path/to/code --dry-run` works
