### ISSUE TITLE
Unknown token

### ISSUE THREAD

**Issue by umpirsky** [umpirsky/Symfony-Upgrade-Fixer#5]
In https://github.com/umpirsky/Symfony-Upgrade-Fixer/blob/master/src%2FSymfony%2FUpgrade%2FFixer%2FFormTypeNamesFixer.php#L132 there is hardcoded token id.

Should be one of http://php.net/manual/en/tokens.php probably, but `token_name(10002)` returns `UNKNOWN`.

On my local server, it's 10007, on Travis 10002, both unknown.

**Comment by lyrixx** [comment]
@nicolas-grekas : Do you have an idea?

**Comment by nicolas-grekas** [comment]
Looking very quickly, I'd say the inline 10002 should be replaced by T_CLASS...

**Comment by umpirsky** [comment]
@nicolas-grekas Nope, `T_CLASS` = 356, `T_CLASS_C` = 366.

I am trying to match `MyClass::class` of PHP 5.6, `T_CLASS` and  `T_CLASS_C` existed before, this is some new token I guess.

Thanks for looking into it! :+1:

**Comment by nicolas-grekas** [comment]
`MyClass::class` is three tokens: T_STRING + T_DOUBLE_COLON + T_CLASS

**Comment by umpirsky** [comment]
@nicolas-grekas Looks like last one is not `T_CLASS`. :(

**Comment by nicolas-grekas** [comment]
https://3v4l.org/p8nPF

**Comment by umpirsky** [comment]
@nicolas-grekas True.

I added a test case in https://github.com/umpirsky/Symfony-Upgrade-Fixer/blob/fix/issue-5/tests/Symfony/Upgrade/Test/Fixer/FormTypeNamesFixerTest.php#L9-L15.

Output is:

```
Symfony\CS\Tokenizer\Token {#141
  -content: "TextType"
  -id: 308
  -isArray: true
  -line: 16
}
Symfony\CS\Tokenizer\Token {#142
  -content: "::"
  -id: 382
  -isArray: true
  -line: 16
}
Symfony\CS\Tokenizer\Token {#143
  -content: "class"
  -id: 10007
  -isArray: true
  -line: 16
}
356
```

Notice `  -id: 10007` where `  -id: 356` is expected.

**Comment by umpirsky** [comment]
Fixed, it was CS fixers [ClassConstant](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3d666f10aa4d1cc545877351dc6cbcf036b524b1/Symfony/CS/Tokenizer/Transformer/ClassConstant.php) transformer.

**Comment by umpirsky** [comment]
Thanks for your help @lyrixx @nicolas-grekas. :+1:
